### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by luckymancvp** [Guiaki/BombCryptoCaptchaSolver#2]
Thank for your repo !

I've cloned it to my machine, and run but I had an error.  Do you have any suggestion
```
D:\Projects\BombCryptoCaptchaSolver>python captchaSolver.py
Traceback (most recent call last):
  File "D:\Projects\BombCryptoCaptchaSolver\captchaSolver.py", line 195, in <module>
    number = numberOcr(img, "hsvOcr")
  File "D:\Projects\BombCryptoCaptchaSolver\captchaSolver.py", line 113, in numberOcr
    positions = locateAll("%s/%s.png" % (folder, number), img, confidence=thresh)
  File "D:\Projects\BombCryptoCaptchaSolver\captchaSolver.py", line 87, in locateAll
    res = cv2.matchTemplate(img, template, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'
```

**Comment by TheMegafuji** [comment]
You've figured out what was the problem? If you don't mind sharing its a good thing to have the solution.

**Comment by luckymancvp** [comment]
> You've figured out what was the problem? If you don't mind sharing its a good thing to have the solution.

Thanks for your great work. Because I tested many times and forgot click connet wallet button so It didn't show captcha

==> error
