### ISSUE TITLE
I've got error

### ISSUE THREAD

**Issue by Miracle1981** [Guiaki/BombCryptoCaptchaSolver#4]
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

======= RESTART: C:\script\BombCryptoCaptchaSolver-main\captchaSolver.py =======
Traceback (most recent call last):
  File "C:\script\BombCryptoCaptchaSolver-main\captchaSolver.py", line 194, in <module>
    img = sweepScreen(m)
  File "C:\script\BombCryptoCaptchaSolver-main\captchaSolver.py", line 127, in sweepScreen
    res = locate("Recognition/robot.png", im, confidence=0.8)
  File "C:\script\BombCryptoCaptchaSolver-main\captchaSolver.py", line 78, in locate
    array = locateAll(tmpName, img, confidence)
  File "C:\script\BombCryptoCaptchaSolver-main\captchaSolver.py", line 93, in locateAll
    if mask[pt[1] + int(round(h / 2)), pt[0] + int(round(w / 2))] != 255:
IndexError: index 160 is out of bounds for axis 1 with size 160

**Comment by TheMegafuji** [comment]
Try uninstalling python 3.10 and using 3.9, check if works
